### ISSUE TITLE
『原创』和手动试黑卡说拜拜，高效率账号检测 —— MineSky Check - MineSky Blog - 一条有着远大理想的咸鱼的博客

### ISSUE THREAD

**Issue by wjy20030407** [wjy20030407/MineSkyBlog-Comment#4]
https://blog.minesky.cn/MineSkyCheck/ 

 看到QQ交流群里有许多萌新反应账号太垃圾经常暴毙，一堆号里面才试出来几个能用的，由此我就简单的写了一个我的世界账号检测工具，实现了多线程、代理测号等功能。当前版本：1.0看到QQ交流群里有许多萌新反应账号太垃圾经常暴毙，一堆号里面才试出来几个能用的，由此我就简单的写了一个我的世界账号检测工具，实现了多线程、代理测号等功能。  ##主要功能Welcome to Hexo! This is you

**Comment by Jointthin** [comment]
整体还不错，希望再出xp专版，xp安装不了net4.6.1
